#!/usr/bin/env bash
if test $# -ge 4
then
    echo "params error, only one or nothing."

elif [ ${#@} -eq 1 ] && [ "${@#"--help"}" = "" ]
then
  printf -- '--------------------------------------\n';
  printf -- '--help           获取帮助\n'
  printf -- '-c [commit-id]   cherry-pick\n'
  printf -- '-d [branch-name] 删除本地的分支'
  printf -- '--------------------------------------\n';
  exit 0;

#logcat
elif [ ${#@} -eq 1 ] && test "-l" = $1 
then 
    adb logcat 

elif test $# -eq 2 && test "-c" = $1 
then 
    git cherry-pick $2

elif test $# -eq 2 && test "-d" = $1
then
    git branch -D $2

else 
    echo '????'
fi

